

CREATE TABLE USERS (
	ID				INT				NOT NULL AUTO_INCREMENT,
	LOGIN			VARCHAR(20)			NOT NULL,
	PASSWORD		VARCHAR(2048)			NOT NULL,
	TYPE			VARCHAR(20)			NOT NULL,
	NAME			VARCHAR(20)			NOT NULL,

	CONSTRAINT PK_USERS PRIMARY KEY (ID)
);

CREATE TABLE CARS (
	ID				INT				NOT NULL AUTO_INCREMENT,
	NAME			VARCHAR(20)			NOT NULL,
	TYPE			VARCHAR(20)			NOT NULL,
	COULEUR			VARCHAR(20)			NOT NULL,

	CONSTRAINT PK_CARS PRIMARY KEY (ID)
);

CREATE TABLE REFRESH_TOKEN (
	ID				INT					NOT NULL AUTO_INCREMENT,
	RT				VARCHAR(50)			NOT NULL,
	EXPIRATION		VARCHAR(14)			NOT NULL,
	USER			INT					NOT NULL,

	CONSTRAINT PK_RT PRIMARY KEY (ID),
    CONSTRAINT FK_RT_USER__USER_ID FOREIGN KEY (USER) REFERENCES users(ID),
    CONSTRAINT UK_RT_USER UNIQUE (USER)
);
